# Generated by Django 5.1.7 on 2025-04-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Dauer in Sekunden', null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('new', 'New on Videoflix'), ('documentary', 'Documentary'), ('drama', 'Drama'), ('romance', 'Romance')], default='new', max_length=20)),
            ],
        ),
    ]
