# Generated by Django 5.1.7 on 2025-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_background',
            field=models.BooleanField(default=False),
        ),
    ]
