# Generated by Django 5.1.7 on 2025-04-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_is_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_background',
        ),
    ]
