# Generated by Django 5.1.7 on 2025-04-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_video_is_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_playlist_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
