# Generated by Django 5.1.7 on 2025-04-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_hls_playlist_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hls_playlist_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
