# Generated by Django 5.1.7 on 2025-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_hls_playlist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file_1080p',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_480p',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_720p',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
